In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge,Lasso,ElasticNet
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_absolute_percentage_error,r2_score

In [2]:
df=pd.read_csv("House_price.csv")

In [6]:
df.head(10)

,Area_sqft,Bedrooms,Bathrooms,House_Age_Years,Parking_Spaces,Distance_to_City_km,Price
0,2649,5,4.0,18,1,18.6,920406
1,4017,1,4.0,3,0,5.2,1077484
2,3463,1,3.0,30,1,9.1,773484
3,800,5,3.5,26,3,11.2,501097
4,2581,3,2.5,10,1,7.4,763041
5,2800,3,2.5,1,0,11.3,908701
6,1003,2,2.5,23,2,24.2,270665
7,1363,5,2.0,14,0,19.7,563236
8,2963,1,1.5,14,2,15.8,601819
9,1146,5,1.0,24,3,22.5,406832

In [7]:
df.tail()

,Area_sqft,Bedrooms,Bathrooms,House_Age_Years,Parking_Spaces,Distance_to_City_km,Price
495,2917,1,3.0,5,3,4.1,872167
496,1891,1,1.5,25,0,13.2,370694
497,2569,2,2.0,11,0,11.3,636800
498,2674,3,3.0,21,2,5.5,802469
499,761,2,1.5,6,2,16.5,334362

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Area_sqft            500 non-null    int64
 1   Bedrooms             500 non-null    int64
 2   Bathrooms            500 non-null    float64
 3   House_Age_Years      500 non-null    int64
 4   Parking_Spaces       500 non-null    int64
 5   Distance_to_City_km  500 non-null    float64
 6   Price                500 non-null    int64
dtypes: float64(2), int64(5)
memory usage: 27.5 KB

In [7]:
df.size

3500

In [8]:
df.describe()

,Area_sqft,Bedrooms,Bathrooms,House_Age_Years,Parking_Spaces,Distance_to_City_km,Price
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,5.000000e+02
mean,2598.134000,3.022000,2.557000,14.976000,1.44800,12.838600,7.470893e+05
std,1102.979986,1.460748,0.869922,8.969075,1.12687,6.974529,2.388841e+05
min,601.000000,1.000000,1.000000,0.000000,0.00000,1.000000,2.236370e+05
25%,1674.250000,2.000000,2.000000,7.000000,0.00000,6.475000,5.621275e+05
50%,2575.000000,3.000000,2.500000,14.000000,1.00000,12.900000,7.456445e+05
75%,3575.250000,4.000000,3.500000,23.000000,2.00000,19.000000,9.271915e+05
max,4500.000000,5.000000,4.000000,30.000000,3.00000,24.900000,1.335513e+06

In [8]:
df.isnull().sum()

Area_sqft              0
Bedrooms               0
Bathrooms              0
House_Age_Years        0
Parking_Spaces         0
Distance_to_City_km    0
Price                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
X=df.drop('Price',axis=1)
y=df.Price

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.8,random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
scaler = StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [22]:
poly = PolynomialFeatures(degree=4,include_bias=False )

  
X_train_poly = poly.fit_transform(X_train_scaled) 
X_test_poly = poly.transform(X_test_scaled) 
  
print("Original Features :", X_train.shape[1])
print("Polynomial Features :", X_train_poly.shape[1])

Original Features : 6
Polynomial Features : 209

In [13]:
ridge=Ridge(alpha=1.0)
model=LinearRegression

In [25]:
linear = LinearRegression() 
  
linear.fit(X_train_poly, y_train) 
  
train_pred = linear.predict(X_train_poly)
test_pred = linear.predict(X_test_poly) 
  
train_r2 = r2_score(y_train, train_pred) 
test_r2 = r2_score(y_test, test_pred) 
  
print("LINEAR REGRESSION")
print("Training R2 :", round(train_r2,4)) 
print("Testing R2 :", round(test_r2,4))

LINEAR REGRESSION
Training R2 : 1.0
Testing R2 : 0.7099

In [27]:
ridge.fit(X_train_scaled, y_train)
ridge_pred = ridge.predict(X_test_scaled)
ridge_mae=mean_absolute_error(y_test,ridge_pred)
ridge_mse=mean_squared_error(y_test,ridge_pred)
ridge_rmse=ridge_mse** 0.5
ridge_r2=r2_score(y_test,ridge_pred)
n=X_test.shape[0]
p=X_test.shape[1]
ridge_adj_r2=1-((1-ridge_r2)*(n-1)/(n-p-1))
ridge_train = r2_score(y_train, train_pred)
ridge_test = r2_score(y_test, test_pred) 
print("--------RIDGE REGRESSION---------")
print("MAE:",ridge_mae)
print("MSE:",ridge_mse)
print("RMSE:",ridge_rmse)
print("R2 SCore:",ridge_r2)
print("Adjusted R2:",ridge_adj_r2)
print("Training R2 :", round(ridge_train,4))
print("Testing R2 :", round(ridge_test,4)) 
print("\nRidge Coefficients:")
for feature, coef in zip(
    X.columns,
    ridge.coef_
):
    print(feature,":",coef)

--------RIDGE REGRESSION---------
MAE: 40631.987841394184
MSE: 2650911954.739577
RMSE: 51487.00763046515
R2 SCore: 0.9515507695177914
Adjusted R2: 0.9508110866096661
Training R2 : 1.0
Testing R2 : 0.7099

Ridge Coefficients:
Area_sqft : 205497.52437102358
Bedrooms : 59429.862715878044
Bathrooms : 51436.11701188389
House_Age_Years : -62989.76195478895
Parking_Spaces : 11797.678431211154
Distance_to_City_km : -42114.730136586026

In [30]:
lasso=Lasso(alpha=1000)
lasso.fit(X_train_scaled, y_train)
lasso_pred=lasso.predict(X_test_scaled)
lasso_mae =mean_absolute_error(y_test,lasso_pred)
lasso_mse =mean_squared_error(y_test,lasso_pred)
lasso_rmse=lasso_mse ** 0.5
lasso_r2=r2_score(y_test,lasso_pred)
lasso_adj_r2=1-((1-lasso_r2)*(n-1)/(n-p-1))
lasso_train = r2_score(y_train, train_pred) 
lasso_test = r2_score(y_test, test_pred) 
print("-----LASSO REGRESSION--------")
print("MAE:",lasso_mae)
print("MSE:",lasso_mse)
print("RMSE:",lasso_rmse)
print("R2 Score:",lasso_r2)
print("Adjusted R2:",lasso_adj_r2)
print("Training R2 :", round(lasso_train,4)) 
print("Testing R2 :", round(lasso_test,4)) 
print("n\Lasso Coefficients:")
for feature, coef in zip(
    X.columns,
    lasso.coef_
):
    print(feature,":",coef)

-----LASSO REGRESSION--------
MAE: 40667.373954044946
MSE: 2653404211.097512
RMSE: 51511.20471409606
R2 Score: 0.9515052199466371
Adjusted R2: 0.9507648416252117
Training R2 : 1.0
Testing R2 : 0.7099
n\Lasso Coefficients:
Area_sqft : 206741.94385501425
Bedrooms : 58924.856146325634
Bathrooms : 50785.27653779255
House_Age_Years : -62377.595231489606
Parking_Spaces : 10912.698368195815
Distance_to_City_km : -41530.481858028535

In [31]:
elastic = ElasticNet(alpha=0.1,l1_ratio=0.5)
elastic.fit(X_train_scaled,y_train)
elastic_pred=elastic.predict(X_test_scaled)
elastic_mae=mean_absolute_error(y_test,elastic_pred)
elastic_mse=mean_squared_error(y_test,elastic_pred)
elastic_rmse=elastic_mse ** 0.5
elastic_r2=r2_score(y_test,elastic_pred)
elastic_adj_r2=1-((1-elastic_r2)*(n-1)/(n-p-1))
elastic_train = r2_score(y_train, train_pred)
elastic_test = r2_score(y_test, test_pred) 
print("-------ELASTIC NET REGRESSION-------")
print("MAE:",elastic_mae)
print("MSE:",elastic_mse)
print("RMSE:",elastic_rmse)
print("R2:",elastic_r2)
print("Adjusted R2:",elastic_adj_r2)
print("Training R2 :", round(elastic_train,4)) 
print("Testing R2 :", round(elastic_test,4)) 
  


print("n\ElasticNet Coefficients:")
for feature ,coef in zip(
    X.columns,
    elastic.coef_
):
    print(feature,":",coef)

-------ELASTIC NET REGRESSION-------
MAE: 41501.022016171344
MSE: 2734527534.7023573
RMSE: 52292.710148761245
R2: 0.9500225744759767
Adjusted R2: 0.9492595603458389
Training R2 : 1.0
Testing R2 : 0.7099
n\ElasticNet Coefficients:
Area_sqft : 198029.22721350426
Bedrooms : 57768.10719447161
Bathrooms : 50451.679531958835
House_Age_Years : -61811.506337757746
Parking_Spaces : 10978.327208679364
Distance_to_City_km : -40223.24026078453

In [32]:
results=pd.DataFrame({"Model":["Ridge","Lasso","ElasticNet"],"MAE":[ridge_mae,lasso_mae,elastic_mae],"MSE":[ridge_mse,lasso_mse,elastic_mse],"RMSE":[ridge_rmse,lasso_rmse,elastic_rmse],"R2":[ridge_r2,lasso_r2,elastic_r2],"Adjusted R2":[ridge_adj_r2,lasso_adj_r2,elastic_adj_r2]
                     }) 
print(results)

        Model           MAE           MSE          RMSE        R2  Adjusted R2
0       Ridge  40631.987841  2.650912e+09  51487.007630  0.951551     0.950811
1       Lasso  40667.373954  2.653404e+09  51511.204714  0.951505     0.950765
2  ElasticNet  41501.022016  2.734528e+09  52292.710149  0.950023     0.949260

In [34]:
comparison = pd.DataFrame({ 
  
    "Model":[ 
        "Linear Regression", 
        "Ridge", 
        "Lasso", 
        "Elastic Net" 
    ], 
  
    "Train R2":[train_r2,ridge_train,lasso_train,elastic_train], "Test R2":[test_r2,ridge_test,         lasso_test,         elastic_test 
    ] 
}) 
  
print(comparison)

               Model  Train R2   Test R2
0  Linear Regression       1.0  0.709908
1              Ridge       1.0  0.709908
2              Lasso       1.0  0.709908
3        Elastic Net       1.0  0.709908